{{- if not (empty (.Files.Glob "files/*")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-files
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- range $path, $_ :=  .Files.Glob  "files/*" }}
  {{ $path | base }}: {{ $.Files.Get $path | toJson }}
  {{- end }}
{{- end }}
