{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            app: {{ include "common.name" . }}
            release: {{ .Release.Name }}
          annotations:
            {{- include "common.annotations" . | nindent 12 }}
        spec:
          {{- if .Values.serviceAccount.enabled }}
          serviceAccountName: {{ .Values.serviceAccount.name | default ( include "common.fullname" . ) }}
          {{- end }}
          restartPolicy: Never # don't let the Pod automatically restart failed containers, the job will restart the Pod instead
          volumes:
            {{- if not (empty (.Files.Glob "files/*")) }}
            - name: files
              configMap:
                name: {{ include "common.name" . }}-files
                defaultMode: 0755
            {{- end }}
          containers:
            - name: job
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              # workingDir: /app
              command:
                - /bin/bash
                - -ec
                - |-
                  echo "hello from cronjob"
                  sleep 5
                  echo "done"
              env:
              {{- range $key, $value := .Values.env }}
                - name: {{ $key | quote }}
                  value: {{ $value | quote }}
              {{- end }}
              volumeMounts:
                {{- if not (empty (.Files.Glob "files/*")) }}
                # - name: files
                #   mountPath: /app
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
{{- end }}
