{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type:  RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "common.name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- include "common.annotations" . | nindent 8 }}
        {{- if .Values.metrics.prometheusAnnotations.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: "{{ .Values.metrics.prometheusAnnotations.path | default "/prometheus" }}"
        prometheus.io/port: "{{ .Values.metrics.prometheusAnnotations.port | default "7080" }}"
        {{- end }}
        {{- if .Values.aws.iamRole }}
        iam.amazonaws.com/role: {{ .Values.aws.iamRole }}
        {{- end }}
        {{- if not (empty (.Files.Glob "files/*")) }}
        # if the configmap changes, the checksum will also force a redeployment of the pods to pick up the changes
        checksum/configmap-files: {{ include (print $.Template.BasePath "/configmap-files.yaml") . | sha256sum }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name | default ( include "common.fullname" . ) }}
      {{- end }}
      volumes:
        {{- if not (empty (.Files.Glob "files/*")) }}
        - name: files
          configMap:
            name: {{ include "common.name" . }}-files
            # defaultMode: 0644
        {{- end }}
        {{- if or .Values.logging.loggingSidecarEnabled .Values.logging.structuredLoggingSidecarEnabled .Values.logging.accesslogSidecarEnabled .Values.logging.managementAccesslogSidecarEnabled }}
        - name: log
          emptyDir: {}
        {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.overrideDefaultEntrypoint }}
          command:
            - "node"
            - "/app/server/entry.mjs"
#            - "java"
#            - "-XX:+HeapDumpOnOutOfMemoryError"
#            - "-XX:HeapDumpPath=$(LOG_PATH)"
#            - "-XX:+UseContainerSupport"
#            - "-XX:MinRAMPercentage=$(JAVA_MIN_RAM_PERCENTAGE)"
#            - "-XX:MaxRAMPercentage=$(JAVA_MAX_RAM_PERCENTAGE)"
#            - "-Dlogging.path=$(LOG_PATH)"
#            - "-Dhttp.proxyHost=$(JAVA_PROXY_HOST)"
#            - "-Dhttp.proxyPort=$(JAVA_PROXY_PORT)"
#            - "-Dhttps.proxyHost=$(JAVA_PROXY_HOST)"
#            - "-Dhttps.proxyPort=$(JAVA_PROXY_PORT)"
#            - "-Dhttp.nonProxyHosts=$(JAVA_NO_PROXY)"
#            - "-jar"
#            - "/app/application.jar"
          {{- end }}
          envFrom:
            - configMapRef:
                name: consul-setup # gets values from consul-setup repo
                optional: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-management
              containerPort: 7080
              protocol: TCP
            # - name: grpc
            #   containerPort: 8090
            #   protocol: TCP
            # - name: grpc-management
            #   containerPort: 7090
            #   protocol: TCP
          volumeMounts:
            {{- if not (empty (.Files.Glob "files/*")) }}
            # you can mount the whole directory with the contents of the configmap, or just single files (usefule if you want to mount them into existing directories where there are other files already)
            # - name: files
            #   mountPath: /etc/my-files
            # - name: files
            #   mountPath: /etc/my-files/some-file.txt
            #   subPath: some-file.txt
            {{- end }}
            {{- if or .Values.logging.loggingSidecarEnabled .Values.logging.structuredLoggingSidecarEnabled .Values.logging.accesslogSidecarEnabled .Values.logging.managementAccesslogSidecarEnabled }}
            - name: log
              mountPath: /tmp
            {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.probes.liveness.port }}
            initialDelaySeconds: 15
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.probes.readiness.port }}
            initialDelaySeconds: 15
          {{- end }}
          lifecycle:
            preStop:
              exec:
                # Make the service stop serving requests before shutdown has started
                # Recommended by Spring:
                # https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html#cloud-deployment-kubernetes-container-lifecycle
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.logging.accesslogSidecarEnabled }}
        {{- include "common.sidecar.tail" (dict "containerName" "access" "path" "/tmp/access.log") | nindent 8 -}}
        {{- end }}
        {{- if .Values.logging.managementAccesslogSidecarEnabled }}
        {{- include "common.sidecar.tail" (dict "containerName" "management" "path" "/tmp/management_access.log") | nindent 8 -}}
        {{- end }}
        {{- if .Values.logging.loggingSidecarEnabled }}
        {{- include "common.sidecar.tail" (dict "containerName" "logger" "path" "/tmp/application.log") | nindent 8 -}}
        {{- end }}
        {{- if .Values.logging.structuredLoggingSidecarEnabled }}
        {{- include "common.sidecar.tail" (dict "containerName" "jsonlogs" "path" "/tmp/application-logstash.log") | nindent 8 -}}
        {{- end }}
        {{- if and .Values.hpa.enabled .Values.hpa.debugContainer.enabled }}
        - name: hpa-debug
          image: {{ .Values.hpa.debugContainer.image }}
          args:
            - --port={{ .Values.hpa.debugContainer.port }}
          resources:
        {{- toYaml .Values.hpa.debugContainer.resources | nindent 12 }}
        {{- end }}
      {{- if .Values.affinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: {{ include "common.name" . }}
                    release: {{ .Release.Name }}
                topologyKey: failure-domain.beta.kubernetes.io/zone
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: {{ include "common.name" . }}
                    release: {{ .Release.Name }}
                topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- if .Values.dnsConfig.enabled }}
      dnsConfig:
      {{- toYaml .Values.dnsConfig.config | nindent 8 }}
      {{- end }}
{{- end }}
