replicaCount: 1
ingress:
  internal:
    enabled: true
    ingressClass: internal
    hostname: wheel-of-names.internal.pre.k-cloud.io
    tls:
      enabled: true
      secretName: wheel-of-names-internal-tls
    annotations:
      cert-manager.io/cluster-issuer: managed
  corp:
    enabled: true
    ingressClass: corp
    hostname: wheel-of-names.corp.pre.k-cloud.io
    tls:
      enabled: true
      secretName: wheel-of-names-corp-tls
    annotations:
      cert-manager.io/cluster-issuer: managed

resources:
 limits:
   cpu: 1000m
   memory: 2Gi
 requests:
   cpu: 500m
   memory: 1Gi

aws:
  enabled: true
  iamRole: arn:aws:iam::303312988286:role/kaos-wheel-of-names

env:
  # This value tells the container which environment is using and is used for picking the correct configuration when running the container.
  RUNTIME_ENV: "nonprod"
