name: KA Renovate

on:
  # Customize based on your team/repository policy
  workflow_dispatch:
    inputs:
      log_level:
        description: "Log level passed to Renovate"
        required: false
        default: info
  schedule:
    - cron: "0 9-17 * * 1-5" # Runs every hour from 9 AM to 5 PM, Monday to Friday

jobs:
  call-renovate-bot:
    uses: Kleinanzeigen/renovate/.github/workflows/ka-renovate-template.yaml@main # Uses reusable-workflow defined in Kleinanzeigen/renovate repository
    secrets: inherit # Automatically pass required secrets from organizational defined secrets
    with:
      log_level: ${{ inputs.log_level || 'info' }}
