name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
  ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

jobs:
  build:
    runs-on: [medium]
    env:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v6

      - name: Set up Node.js 🛠️
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Install dependencies 📦
        run: npm ci

      - name: Run lint 🧹
        run: npm run lint

      # - name: Run tests 🧪
      #   run: npm run test:ci

      - name: Build 🏗️
        run: npm run build

      # - name: Run ES-Check 🔍
      #   run: npm run es-check

  # e2e:
  #   runs-on: [big]
  #   container:
  #     image: dockerhub.containers.mpi-internal.com/cypress/browsers:latest # by using this image we can skip installing chrome
  #   env:
  #     CYPRESS_BASE_URL: http://localhost:3000/
  #   steps:
  #     - name: Checkout repository 🛎️
  #       uses: actions/checkout@v6
  #     - name: Set up Node.js 🛠️
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version-file: .node-version
  #         cache: "npm"

  #     - name: Install dependencies 📦
  #       run: npm ci

  #     - name: Cypress run
  #       id: cypress-run
  #       uses: cypress-io/github-action@v6
  #       with:
  #         browser: chrome
  #         wait-on: ${{ env.CYPRESS_BASE_URL }}
  #         wait-on-timeout: 30
  #         start: npm run dev
  #       env:
  #         UNAUTHORIZED: 0